# Generated by Django 2.1.5 on 2019-01-28 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='amount',
            new_name='quantity',
        ),
    ]
